import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import path from 'node:path';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import api from './routes/api.js';
const app = express(); const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const clientRoot = path.join(root, 'client'); const clientDir = existsSync(path.join(clientRoot, 'dist')) ? path.join(clientRoot, 'dist') : clientRoot;
app.use(cors()); app.use(express.json({ limit: '1mb' })); app.use('/api', api); app.use(express.static(clientDir)); app.get('/{*path}', (_req, res) => res.sendFile(path.join(clientDir, 'index.html')));
if (process.env.MONGODB_URI) mongoose.connect(process.env.MONGODB_URI).then(() => console.log('MongoDB connected')).catch((error) => console.warn(`MongoDB unavailable: ${error.message}`));
app.listen(process.env.PORT || 3000, () => console.log(`MediNav running at http://localhost:${process.env.PORT || 3000}`));
